apiVersion: v1
kind: ConfigMap
metadata:
  name: soda-checks
  namespace: datajegerne
data:
  metrics.yaml: |
    checks for duplikater_etterlevelse:
      # Standard numeric opplegg
      - row_count = 0:
          name: "Tabellen inneholder kun etterlevelsesdokumenter der det er flere besvarelser per krav. Om det er flere enn null rader må vi inn og slette i databasen."

